### PR TITLE
rename module type to types

### PR DESCRIPTION
**Pull request by joelberkeley**
`import type` clashes with the inbuilt `type`. This PR renames the module to `types`

### CODE REVIEW

**Review by hstojic — COMMENTED** [review]
I understand its not a good practice to have the same name as a builtin function, but to me it seems there shouldn't be any clash, usually we are having statements like
`from trieste.type import TensorType` - here there is no confusion, right?
did you ever encounter an issue with this?

**Comment by joelberkeley** [comment]
in the trust region PR, I had a case where I couldn't import `State` from `type` as is because there was already a `State` class in rule.py. I ended up going with `import type as types` ... `types.State`. It's an edge case, no doubt, just thought it would be good to do

**Comment by hstojic** [comment]
ok, fair enough, better to be on the safe side and do these things early in the development

**Review by hstojic — APPROVED** [review]
good to go, let me know when you are ready to merge

**Comment by joelberkeley** [comment]
ready to merge

**Pull request merged**
