### PR TITLE
rename datasets module to data

### PR DESCRIPTION
**Pull request by joelberkeley**

### CODE REVIEW

**Review by awav — COMMENTED** [review]
Why?

**Comment by joelberkeley** [comment]
> Why?

Because it's shorter and conveys the meaning just as well. It also aligns with `tf.data.Dataset`

**Comment by joelberkeley** [comment]
I'm also going to make another PR to rename all the other mentions of `dataset[s]` to `data`, for the same reasons

**Comment by awav** [comment]
> I'm also going to make another PR to rename all the other mentions of `dataset[s]` to `data`, for the same reasons

Why another PR and not here?

**Comment by joelberkeley** [comment]
mostly for the reviewer's sanity

**Comment by joelberkeley** [comment]
thought it would be easier to see mistakes if it's done separately

also I thought the other change was slightly more controversial so I thought I'd not lump them together

**Review by ChrisMorter — APPROVED** [review]
LGTM

**Pull request merged**
