### PR TITLE
fix formatting in inequality notebook

### PR DESCRIPTION
**Pull request by joelberkeley**
@vpicheny don't forget the `# %%` for code cells. This code appears as comments on the website

@uri-granta fyi the doc build didn't pick this up

### CODE REVIEW

**Review by hstojic — APPROVED** [review]
looks good - ok to merge?

**Comment by joelberkeley** [comment]
@hstojic ready to merge

**Comment by uri-granta** [comment]
Sorry didn't spot this until now. I've just put in a fix for this myself!

**Comment by hstojic** [comment]
@uri-granta if you have merged in your already, perhaps you can close this one?

**Comment by uri-granta** [comment]
(As an aside, there is no way the build would ever pick this up, as the document was syntactically valid. Just gives an extra reason why it would be good to also publish the develop docs somewhere. Either way, I've added an explicit step to the release process to build the docs locally and read through them all before any release.)

**Pull request closed without merging**
