### PR TITLE
restrict tensorflow-probability to <0.14

### PR DESCRIPTION
**Pull request by tensorlicious**
tensorflow-probability >= 0.14 has breaking changes to API.

### CODE REVIEW

**Comment by tensorlicious** [comment]
actually this may be better handled in `gpflux`.

**Review by henrymoss — APPROVED** [review]
LGTM

**Comment by tensorlicious** [comment]
I'd suggest we hold off on merging this until we coordinate with gpflux.

**Comment by hstojic** [comment]
@tensorlicious this PR is now obsolete, right?

**Comment by tensorlicious** [comment]
> @tensorlicious this PR is now obsolete, right?

yes. Closing.

**Pull request closed without merging**
